#!/usr/bin/env python3
"""把 README 的名單同步成 credits.json 的內容。

為什麼需要
----------
同一份名單有兩個地方要改：遊戲內的 credits.json，以及 README。手動維護兩份
的結果就是它們會分岔——實際發生過：遊戲裡加了人、換了人，README 還停在
好幾版之前，看的人以為自己沒被收錄。

一份資料、一個來源。credits.json 是真的那一份（遊戲讀它），README.md 與
README.en.md 由它產生。英文版只換表頭與分類名稱，名字照 credits.json 原樣。

用法
----
    python tools/sync-credits.py            # 改寫兩份 README
    python tools/sync-credits.py --check    # 只檢查，不一致回傳 1（給 CI 用）
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CREDITS = ROOT / "src/main/resources/assets/wynnchayuan/credits.json"

BEGIN = "<!-- credits:begin -->"
END = "<!-- credits:end -->"

# 檔案 -> 語言。
TARGETS = {
    ROOT / "README.md": "zh",
    ROOT / "README.en.md": "en",
}

# 英文版的分類名稱。認不出來的分類照原文顯示——寧可一格中文，也不要瞎翻。
ROLE_EN = {
    "開發者": "Developers",
    "贊助者": "Sponsors",
    "貢獻者": "Contributors",
    "資料來源": "Data sources",
}
NAME_EN = {
    "Wynntils（物品／技能 CDN）": "Wynntils (item / ability CDN)",
}


def render(lang: str = "zh") -> str:
    data = json.loads(CREDITS.read_text(encoding="utf-8"))
    en = lang == "en"
    note = ("<!-- Generated by tools/sync-credits.py from credits.json - do not edit by hand. -->"
            if en else
            "<!-- 這一段由 tools/sync-credits.py 從 credits.json 產生，不要手動改。 -->")
    header = "| Name | Minecraft ID |" if en else "| 名稱 | Minecraft ID |"
    lines = [BEGIN, "", note]
    for section in data.get("sections", []):
        members = section.get("members", [])
        if not members:
            continue
        role = ROLE_EN.get(section["role"], section["role"]) if en else section["role"]
        lines += ["", f"### {role}", "", header, "|---|---|"]
        for m in members:
            name = NAME_EN.get(m["name"], m["name"]) if en else m["name"]
            mc = m.get("mc", "")
            lines.append(f"| {name} | " + (f"`{mc}` |" if mc else "— |"))
    footer = ("Translate one line and you are on this list. See [CONTRIBUTING.en.md](CONTRIBUTING.en.md)."
              if en else
              "翻一條就會出現在這裡。見 [CONTRIBUTING.md](CONTRIBUTING.md)。")
    lines += ["", footer, "", END]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    status = 0
    for path, lang in TARGETS.items():
        text = path.read_text(encoding="utf-8")
        if BEGIN not in text or END not in text:
            print(f"{path.name} 裡找不到 {BEGIN} / {END} 標記，先手動放一次。")
            return 2

        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        updated = head + render(lang) + tail

        if updated == text:
            print(f"{path.name} 的名單已經是最新的。")
            continue
        if "--check" in argv:
            print(f"{path.name} 的名單與 credits.json 不一致 —— 跑 python tools/sync-credits.py")
            status = 1
            continue
        path.write_text(updated, encoding="utf-8", newline="\n")
        print(f"已更新 {path.name} 的名單。")
    return status


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
